name: Release

permissions:
  contents: read
  packages: write
  id-token: write

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Compile
        run: npx tsc

      - name: Test
        run: npm test

      - name: Extract version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Build artifact
        run: npm run build

      - name: Install Syft
        run: curl -sSfL https://get.anchore.io/syft | sudo sh -s -- -b /usr/local/bin

      - name: Install Grype
        run: curl -sSfL https://get.anchore.io/grype | sudo sh -s -- -b /usr/local/bin

      - name: Install Grant
        run: curl -sSfL https://get.anchore.io/grant | sudo sh -s -- -b /usr/local/bin

      - name: Run Syft
        run: npm run sbom

      - name: Run Grype
        run: npm run scan

      - name: Run Grant
        run: npm run licenses

      - name: Build versioned and latest release copies
        run: bash release.sh

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Upload to Cloudflare R2
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          wrangler r2 object put ${{ vars.CLOUDFLARE_R2_BUCKET_NAME }}/mikroroom_${VERSION}.zip --file=mikroroom_${VERSION}.zip --jurisdiction=eu --remote
          wrangler r2 object put ${{ vars.CLOUDFLARE_R2_BUCKET_NAME }}/mikroroom_latest.zip --file=mikroroom_latest.zip --jurisdiction=eu --remote
          wrangler r2 object put ${{ vars.CLOUDFLARE_R2_BUCKET_NAME }}/install.sh --file=install.sh --jurisdiction=eu --remote

      #- name: Publish to NPM
      #  run: npm publish --access public

      - name: Notify backoffice API
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          curl -X POST https://api.mikroroom.com/version?version=${VERSION} -H "Authorization: ${{ secrets.MIKROROOM_BACKOFFICE_API_KEY }}"